services:
  - type: web
    name: nave-a-la-deriva
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn missions.e7_drifting_ship:app --host 0.0.0.0 --port $PORT
